/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import java.util.List;
import javaapplication1.DAO.BangDiemDAO;
import javaapplication1.DAO.PhucKhaoDiemDAO;
import javaapplication1.DAO.SinhVienDAO;
import javaapplication1.Pojo.Bangdiem;
import javaapplication1.Pojo.Phuckhao;
import javaapplication1.Pojo.Sinhvien;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class FormPhucKhaoDiemSinhVien extends javax.swing.JFrame {

    /** Creates new form FormPhucKhaoDiemSinhVien */
    public FormPhucKhaoDiemSinhVien() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdGK = new javax.swing.JRadioButton();
        rdCK = new javax.swing.JRadioButton();
        rdDK = new javax.swing.JRadioButton();
        rdALL = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lbMSSV = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        cmbMonHoc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDiemMongMuon = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLyDo = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("MSSV");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Môn học");

        rdGK.setText("Điểm GK");

        rdCK.setText("Điểm CK");

        rdDK.setText("Điểm khác");

        rdALL.setText("Tất cả");
        rdALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdALLActionPerformed(evt);
            }
        });

        jLabel4.setText("Điểm mong muốn");

        lbMSSV.setText("MSSV");

        lbHoTen.setText("HOTEN");

        jLabel7.setText("Cột điểm mong muốn");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtLyDo.setColumns(20);
        txtLyDo.setRows(5);
        jScrollPane1.setViewportView(txtLyDo);

        jLabel5.setText("Lý do (ghi rỏ)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdGK)
                        .addGap(18, 18, 18)
                        .addComponent(rdCK)
                        .addGap(18, 18, 18)
                        .addComponent(rdDK)
                        .addGap(18, 18, 18)
                        .addComponent(rdALL))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMSSV)
                            .addComponent(lbHoTen)
                            .addComponent(cmbMonHoc, 0, 167, Short.MAX_VALUE)
                            .addComponent(txtDiemMongMuon)))
                    .addComponent(btnXacNhan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbMSSV))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbHoTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemMongMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdGK)
                    .addComponent(rdCK)
                    .addComponent(rdDK)
                    .addComponent(rdALL))
                .addGap(42, 42, 42)
                .addComponent(btnXacNhan)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void HienThiThongTin()
    {
        Sinhvien sv = new SinhVienDAO().getByID("1842002");
        lbHoTen.setText(sv.getHoTen());
        lbMSSV.setText(sv.getMssv());
    }
    
    void  HienDanhSachDiem()
    {
       
       List<Bangdiem> list = new BangDiemDAO().getListByMSSV("1842002");
       
       if(list!=null)
       {
           for(Bangdiem item : list)
           {
               cmbMonHoc.addItem(item.getMaBangDiem().split("-")[1].toString());
           }
       }
       
        
        
        
        
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        HienThiThongTin();
        HienDanhSachDiem();
    }//GEN-LAST:event_formWindowOpened

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        
    // TODO add your handling code here:
        Phuckhao pk = new PhucKhaoDiemDAO().TonTai();
        if(pk.getId()!=null)
        {
            String diemLua ="";
            if(rdGK.isSelected())
            {
                diemLua = rdGK.getText();
            }
            else if(rdCK.isSelected())
            {
                diemLua = rdCK.getText();
            }
            else if(rdDK.isSelected())
            {
                diemLua = rdDK.getText();
            }
            else
            {
                diemLua = rdALL.getText();
            }
            pk.getId().setMssv(lbMSSV.getText());
            
               
            Phuckhao pkthem = new Phuckhao(pk.getId(), cmbMonHoc.getSelectedItem().toString() , "Chưa xem", lbHoTen.getText(),diemLua , txtDiemMongMuon.getText(), txtLyDo.getText());
           new      PhucKhaoDiemDAO().ThemChoSinhVien(pkthem);
            JOptionPane.showMessageDialog(null, "Gừi phúc khảo thành  công","Thông báo" , JOptionPane.INFORMATION_MESSAGE);
        
            
           }
          else
            {
              JOptionPane.showMessageDialog(null, "Chưa đến ngày phúc khảo xin kiểm tra lai","Thông báo" , JOptionPane.INFORMATION_MESSAGE);
          
                
            }
            
        
        
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void rdALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdALLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPhucKhaoDiemSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cmbMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbMSSV;
    private javax.swing.JRadioButton rdALL;
    private javax.swing.JRadioButton rdCK;
    private javax.swing.JRadioButton rdDK;
    private javax.swing.JRadioButton rdGK;
    private javax.swing.JTextField txtDiemMongMuon;
    private javax.swing.JTextArea txtLyDo;
    // End of variables declaration//GEN-END:variables

}
