/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javaapplication1.DAO.BangDiemDAO;
import javaapplication1.DAO.LopMonHocDAO;
import javaapplication1.DAO.PhucKhaoDiemDAO;
import javaapplication1.Pojo.Bangdiem;
import javaapplication1.Pojo.Lopmonhoc;
import javaapplication1.Pojo.Phuckhao;
import javaapplication1.Pojo.PhuckhaoId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class FormPhucKhaoDiem extends javax.swing.JFrame {

    /**
     * Creates new form FormPhucKhaoDiem
     */
    public FormPhucKhaoDiem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        dtpNgayBD = new com.toedter.calendar.JDateChooser();
        dtpNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachPhucKhao = new javax.swing.JTable();
        txtTenPhucKhao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTrangThai = new javax.swing.JComboBox<>();
        btnCapNhat = new javax.swing.JButton();
        btnXem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setText("Từ ngày");

        jLabel2.setText("Đến ngày");

        tblDanhSachPhucKhao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachPhucKhao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhucKhaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachPhucKhao);

        jLabel3.setText("Tên phúc khảo");

        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa xem", "Cập nhập điểm", "Chưa cập nhật điểm" }));

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        jLabel4.setText("Trạng thái");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(47, 47, 47)
                        .addComponent(btnCapNhat)
                        .addGap(61, 61, 61)
                        .addComponent(btnXem)
                        .addGap(525, 525, 525))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenPhucKhao)
                            .addComponent(dtpNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(479, 479, 479))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dtpNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenPhucKhao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String[] columnNames = { "STT", "Tên phúc khảo","Ngày bắt đầu", "Ngày kết thúc","MSSV","Họ tên","Môn phúc khảo","Cột điểm phúc khảo","Điểm Mong muốn","Lý do" ,"Trạng thái"};

    
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        PhuckhaoId pkid = new PhuckhaoId(txtTenPhucKhao.getText(),dtpNgayBD.getDate(),dtpNgayKT.getDate(),"0");
        Phuckhao pk = new Phuckhao(pkid);
        PhucKhaoDiemDAO pkdao = new PhucKhaoDiemDAO();
        pkdao.ThemChoGiaoVu(pk);
    }//GEN-LAST:event_btnThemActionPerformed

    
    void HienThiTable(List<Phuckhao> list)
    {
        if(list==null)
        {
                  
        TableModel tablemodel = new DefaultTableModel(null, columnNames);
        tblDanhSachPhucKhao.setModel(tablemodel);
        }
String[][] listDataSinhVien = new String[list.size()][11];
    int dem=0;
        for(int i =list.size()-1;i>=0;i--)
        {
            if( list.get(i).getMonPhucKhao()==null)
            {
                continue;
            }
              listDataSinhVien[dem][0] = (dem+1) + "";
              listDataSinhVien[dem][1] =  list.get(i).getId().getMaPhucKhao();
              listDataSinhVien[dem][2] =  list.get(i).getId().getNgayBd().toString();
             
                listDataSinhVien[dem][3] =  list.get(i).getId().getNgayKt().toString();
                        listDataSinhVien[dem][4] =   list.get(i).getId().getMssv();
                 listDataSinhVien[dem][5] =  list.get(i).getHoTen();
              listDataSinhVien[dem][6] =   list.get(i).getMonPhucKhao();
       
                            listDataSinhVien[dem][7] =  list.get(i).getCotDiemPhucKhao();
                            listDataSinhVien[dem][8] =  list.get(i).getDiemMongMuon();
                            listDataSinhVien[dem][9] =  list.get(i).getLyDo();
                            listDataSinhVien[dem][10] =  list.get(i).getTrangThai();  
                            dem++;
        }
        
        
        
        TableModel tablemodel = new DefaultTableModel(listDataSinhVien, columnNames);
        tblDanhSachPhucKhao.setModel(tablemodel);
    }
    
    void LoadSinhVienPhucKhao()
    {
         List<Phuckhao> listpk = new PhucKhaoDiemDAO().getALL();
         
         HienThiTable(listpk);
         
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LoadSinhVienPhucKhao();
    }//GEN-LAST:event_formWindowOpened

    private void tblDanhSachPhucKhaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachPhucKhaoMouseClicked
        // TODO add your handling code here:
        
      
        
      
    }//GEN-LAST:event_tblDanhSachPhucKhaoMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
           int check = tblDanhSachPhucKhao.getSelectedRowCount();
        
        if(check==0)
        {
            JOptionPane.showMessageDialog(null,"Chưa chọn sinh viên phúc khảo","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
          try {
             String mapk =  tblDanhSachPhucKhao.getValueAt(tblDanhSachPhucKhao.getSelectedRow(), 1).toString();
             String ngaybd = tblDanhSachPhucKhao.getValueAt(tblDanhSachPhucKhao.getSelectedRow(), 2).toString();
           String ngakt =  tblDanhSachPhucKhao.getValueAt(tblDanhSachPhucKhao.getSelectedRow(), 3).toString();
          String mssv = tblDanhSachPhucKhao.getValueAt(tblDanhSachPhucKhao.getSelectedRow(), 4).toString();
          
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        Date datebd = sdf.parse(ngaybd);
                        Date datekt = sdf.parse(ngakt);
             
            Phuckhao pk = new PhucKhaoDiemDAO().TimKiem(mapk,datebd,datekt,mssv);
            if(pk.getId()!=null)
            {
                pk.setTrangThai(cmbTrangThai.getSelectedItem().toString());
                new PhucKhaoDiemDAO().Sua(pk);
            }
        } catch (Exception e) {
        }
          JOptionPane.showMessageDialog(null,"Cập  nhật thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        LoadSinhVienPhucKhao();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                   
        HienThiTable( new PhucKhaoDiemDAO().XemPhucKhao(dtpNgayBD.getDate(), dtpNgayKT.getDate()));
    }//GEN-LAST:event_btnXemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPhucKhaoDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPhucKhaoDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXem;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private com.toedter.calendar.JDateChooser dtpNgayBD;
    private com.toedter.calendar.JDateChooser dtpNgayKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSachPhucKhao;
    private javax.swing.JTextField txtTenPhucKhao;
    // End of variables declaration//GEN-END:variables
}
