/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.DAO.*;
import javaapplication1.DAO.LopMonHocDAO;
import javaapplication1.DAO.LophocDAO;
import javaapplication1.Entities.SinhVien;
import javaapplication1.Extension.TxtFileNameFilter;
import javaapplication1.Pojo.Lophoc;
import javaapplication1.Pojo.Lopkhoabieu;
import javaapplication1.Pojo.Lopmonhoc;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Asus
 */
public class FormDanhSachLopHocMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form FormDanhSachLopHocMonHoc
     */
    
      String[] columnNames = { "STT", "MSSV","Họ tên", "Gới tính","CMND" };
    public FormDanhSachLopHocMonHoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cmdLopMonHoc = new javax.swing.JComboBox<>();
        txtMSSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSinhVienMonHoc = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách lớp môn học");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmdLopMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmdLopMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLopMonHocActionPerformed(evt);
            }
        });

        jLabel1.setText("MSSV");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Giới tính");

        jLabel4.setText("CMND");

        tbSinhVienMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbSinhVienMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSinhVienMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSinhVienMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSinhVienMonHoc);

        scrollPane1.add(jScrollPane1);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbNam);
        rdbNam.setText("Nam");

        buttonGroup1.add(rdbNu);
        rdbNu.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cmdLopMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMSSV)
                        .addComponent(txtHoTen)
                        .addComponent(txtCMND, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNu)))
                .addGap(164, 164, 164))
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rdbNam)
                            .addComponent(rdbNu))
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdLopMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     void LoadDuLieuSinHVien(String[] columnNames,String lophoc)
    {
         List<Lopmonhoc> list = new LopMonHocDAO().getByID(cmdLopMonHoc.getSelectedItem().toString());
        
        String[][] listDataSinhVien = new String[list.size()][5];
        for(int i =0;i<list.size();i++)
        {
              listDataSinhVien[i][0] = (i+1) + "";
              listDataSinhVien[i][1] =  list.get(i).getMssv();
              listDataSinhVien[i][2] =  list.get(i).getHoTen();
               
              String gt="Nữ";
              if(list.get(i).getGioiTinh())
              {
                  gt="Nam";
              }
              listDataSinhVien[i][3] = gt;
              listDataSinhVien[i][4] =  list.get(i).getCmnd();
        }
        
        
        
        TableModel tablemodel = new DefaultTableModel(listDataSinhVien, columnNames);
        tbSinhVienMonHoc.setModel(tablemodel);
        
    
    }
    void  HienThiDanhSachLopLenCombobox()
    {
       
        Lopkhoabieu lhocdao = new Lopkhoabieu();
        List<Lopkhoabieu> listlophoc =  new LopKhoaBieuDAO().getALL();
        if(listlophoc==null)
        {
            return;
        }
        for(Lopkhoabieu item :listlophoc)
        {
             cmdLopMonHoc.addItem(item.getMaLopKhoaBieu().toString());
        }
      
    }
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TableModel tablemodel = new DefaultTableModel(null, columnNames);
        tbSinhVienMonHoc.setModel(tablemodel);
        rdbNam.setSelected(true);
        this.setLocationRelativeTo(null);
        HienThiDanhSachLopLenCombobox();
       if(cmdLopMonHoc.getItemCount()>0)
        {
             LoadDuLieuSinHVien(columnNames, cmdLopMonHoc.getSelectedItem().toString());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cmdLopMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLopMonHocActionPerformed
        // TODO add your handling code here:
        LoadDuLieuSinHVien(columnNames, cmdLopMonHoc.getSelectedItem().toString());
    }//GEN-LAST:event_cmdLopMonHocActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if(txtCMND.getText().length()==0||txtMSSV.getText().length()==0||txtHoTen.getText().length()==0)
        {
             JOptionPane.showMessageDialog(null, "Dữ liệu không hợp lệ xin kiểm tra lại","Thông báo" , JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
          Boolean gioiTinh=false;
         if(rdbNam.isSelected())
         {
             gioiTinh =true;
         }
          
         LopMonHocDAO lopmhdao = new LopMonHocDAO();
        Lopmonhoc lopmh = new Lopmonhoc(cmdLopMonHoc.getSelectedItem().toString()+txtMSSV.getText(), txtMSSV.getText(),txtHoTen.getText(), gioiTinh, txtCMND.getText(),cmdLopMonHoc.getSelectedItem().toString());
       lopmhdao.ThemLopMonHoc(lopmh);
             
             
             
        if(cmdLopMonHoc.getItemCount()>0)
        {
             LoadDuLieuSinHVien(columnNames, cmdLopMonHoc.getSelectedItem().toString());
        }
       
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        
        int check = tbSinhVienMonHoc.getSelectedRowCount();
        
        if(check==0)
        {
            return;
        }
        
        try {
            Lopmonhoc svl = new LopMonHocDAO().getByMSSV(tbSinhVienMonHoc.getValueAt(tbSinhVienMonHoc.getSelectedRow(), 1).toString());
            if(svl!=null)
            {
                new LopMonHocDAO().XoaLopMonHoc(svl);
            }
        } catch (Exception e) {
        }
        
        
       
       if(cmdLopMonHoc.getItemCount()>0)
        {
             LoadDuLieuSinHVien(columnNames, cmdLopMonHoc.getSelectedItem().toString());
        }
            
            
        
         
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbSinhVienMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSinhVienMonHocMouseClicked
        // TODO add your handling code here:
         txtMSSV.setText(tbSinhVienMonHoc.getValueAt(tbSinhVienMonHoc.getSelectedRow(), 1).toString());
        txtHoTen.setText(tbSinhVienMonHoc.getValueAt(tbSinhVienMonHoc.getSelectedRow(), 2).toString());
       if(tbSinhVienMonHoc.getValueAt(tbSinhVienMonHoc.getSelectedRow(), 3).toString().contains("Nam"))
        {
            rdbNam.setSelected(true);
        }
        else
        {
             rdbNu.setSelected(true);
        }
        
        txtCMND.setText(tbSinhVienMonHoc.getValueAt(tbSinhVienMonHoc.getSelectedRow(), 4).toString());
       
         
    }//GEN-LAST:event_tbSinhVienMonHocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDanhSachLopHocMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDanhSachLopHocMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDanhSachLopHocMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDanhSachLopHocMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDanhSachLopHocMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmdLopMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tbSinhVienMonHoc;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMSSV;
    // End of variables declaration//GEN-END:variables
}
