package javaapplication1.Pojo;
// Generated Aug 21, 2019 1:01:46 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bangdiem generated by hbm2java
 */
@Entity
@Table(name="bangdiem"
    ,catalog="quanlysinhvien"
)
public class Bangdiem  implements java.io.Serializable {


     private String maBangDiem;
     private String mssv;
     private String hoTen;
     private String diemGk;
     private String diemCk;
     private String diemKhac;
     private String diemTong;

    public Bangdiem() {
    }

	
    public Bangdiem(String maBangDiem) {
        this.maBangDiem = maBangDiem;
    }
    public Bangdiem(String maBangDiem, String mssv, String hoTen, String diemGk, String diemCk, String diemKhac, String diemTong) {
       this.maBangDiem = maBangDiem;
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
     @Id 

    
    @Column(name="MaBangDiem", unique=true, nullable=false)
    public String getMaBangDiem() {
        return this.maBangDiem;
    }
    
    public void setMaBangDiem(String maBangDiem) {
        this.maBangDiem = maBangDiem;
    }

    
    @Column(name="MSSV", length=50)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="HoTen")
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="DiemGK")
    public String getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(String diemGk) {
        this.diemGk = diemGk;
    }

    
    @Column(name="DiemCK")
    public String getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(String diemCk) {
        this.diemCk = diemCk;
    }

    
    @Column(name="DiemKhac")
    public String getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(String diemKhac) {
        this.diemKhac = diemKhac;
    }

    
    @Column(name="DiemTong")
    public String getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(String diemTong) {
        this.diemTong = diemTong;
    }




}


