package javaapplication1.Pojo;
// Generated Aug 21, 2019 1:01:46 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Chucvu generated by hbm2java
 */
@Entity
@Table(name="chucvu"
    ,catalog="quanlysinhvien"
)
public class Chucvu  implements java.io.Serializable {


     private String maChucVu;
     private String tenChucVu;

    public Chucvu() {
    }

	
    public Chucvu(String maChucVu) {
        this.maChucVu = maChucVu;
    }
    public Chucvu(String maChucVu, String tenChucVu) {
       this.maChucVu = maChucVu;
       this.tenChucVu = tenChucVu;
    }
   
     @Id 

    
    @Column(name="MaChucVu", unique=true, nullable=false, length=50)
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }

    
    @Column(name="TenChucVu")
    public String getTenChucVu() {
        return this.tenChucVu;
    }
    
    public void setTenChucVu(String tenChucVu) {
        this.tenChucVu = tenChucVu;
    }




}


