package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Giaovu generated by hbm2java
 */
@Entity
@Table(name="giaovu"
    ,catalog="quanlysinhvien"
)
public class Giaovu  implements java.io.Serializable {


     private String maGiaoVu;
     private String tenGiaoVu;
     private String maChucVu;

    public Giaovu() {
    }

	
    public Giaovu(String maGiaoVu) {
        this.maGiaoVu = maGiaoVu;
    }
    public Giaovu(String maGiaoVu, String tenGiaoVu, String maChucVu) {
       this.maGiaoVu = maGiaoVu;
       this.tenGiaoVu = tenGiaoVu;
       this.maChucVu = maChucVu;
    }
   
     @Id 

    
    @Column(name="MaGiaoVu", unique=true, nullable=false, length=50)
    public String getMaGiaoVu() {
        return this.maGiaoVu;
    }
    
    public void setMaGiaoVu(String maGiaoVu) {
        this.maGiaoVu = maGiaoVu;
    }

    
    @Column(name="TenGiaoVu")
    public String getTenGiaoVu() {
        return this.tenGiaoVu;
    }
    
    public void setTenGiaoVu(String tenGiaoVu) {
        this.tenGiaoVu = tenGiaoVu;
    }

    
    @Column(name="MaChucVu", length=50)
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }




}


