package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Khoabieu generated by hbm2java
 */
@Entity
@Table(name="khoabieu"
    ,catalog="quanlysinhvien"
)
public class Khoabieu  implements java.io.Serializable {


     private KhoabieuId id;
     private String hocKy;
     private Date ngay;
     private String maLop;
     private String phong;

    public Khoabieu() {
    }

	
    public Khoabieu(KhoabieuId id, String hocKy, Date ngay, String maLop) {
        this.id = id;
        this.hocKy = hocKy;
        this.ngay = ngay;
        this.maLop = maLop;
    }
    public Khoabieu(KhoabieuId id, String hocKy, Date ngay, String maLop, String phong) {
       this.id = id;
       this.hocKy = hocKy;
       this.ngay = ngay;
       this.maLop = maLop;
       this.phong = phong;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maKhoaBieu", column=@Column(name="MaKhoaBieu", nullable=false, length=50) ), 
        @AttributeOverride(name="tenMonHoc", column=@Column(name="TenMonHoc", nullable=false, length=100) ) } )
    public KhoabieuId getId() {
        return this.id;
    }
    
    public void setId(KhoabieuId id) {
        this.id = id;
    }

    
    @Column(name="HocKy", nullable=false, length=50)
    public String getHocKy() {
        return this.hocKy;
    }
    
    public void setHocKy(String hocKy) {
        this.hocKy = hocKy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Ngay", nullable=false, length=19)
    public Date getNgay() {
        return this.ngay;
    }
    
    public void setNgay(Date ngay) {
        this.ngay = ngay;
    }

    
    @Column(name="MaLop", nullable=false, length=50)
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    
    @Column(name="Phong")
    public String getPhong() {
        return this.phong;
    }
    
    public void setPhong(String phong) {
        this.phong = phong;
    }




}


