package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lophoc generated by hbm2java
 */
@Entity
@Table(name="lophoc"
    ,catalog="quanlysinhvien"
)
public class Lophoc  implements java.io.Serializable {


     private String maLop;
     private String tenLop;
     private Date year;

    public Lophoc() {
    }

	
    public Lophoc(String maLop, String tenLop) {
        this.maLop = maLop;
        this.tenLop = tenLop;
    }
    public Lophoc(String maLop, String tenLop, Date year) {
       this.maLop = maLop;
       this.tenLop = tenLop;
       this.year = year;
    }
   
     @Id 

    
    @Column(name="MaLop", unique=true, nullable=false, length=50)
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    
    @Column(name="TenLop", nullable=false, length=200)
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Year", length=19)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }




}


