package javaapplication1.Pojo;
// Generated Aug 16, 2019 3:07:40 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lophoc generated by hbm2java
 */
@Entity
@Table(name="lophoc"
    ,catalog="quanlysinhvien"
)
public class Lophoc  implements java.io.Serializable {


     private String maLop;
     private String tenLop;
     private Set<Sinhvien> sinhviens = new HashSet<Sinhvien>(0);

    public Lophoc() {
    }

	
    public Lophoc(String maLop, String tenLop) {
        this.maLop = maLop;
        this.tenLop = tenLop;
    }
    public Lophoc(String maLop, String tenLop, Set<Sinhvien> sinhviens) {
       this.maLop = maLop;
       this.tenLop = tenLop;
       this.sinhviens = sinhviens;
    }
   
     @Id 

    
    @Column(name="MaLop", unique=true, nullable=false, length=50)
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    
    @Column(name="TenLop", nullable=false, length=200)
    public String getTenLop() {
        return this.tenLop;
    }
    
    public void setTenLop(String tenLop) {
        this.tenLop = tenLop;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lophoc")
    public Set<Sinhvien> getSinhviens() {
        return this.sinhviens;
    }
    
    public void setSinhviens(Set<Sinhvien> sinhviens) {
        this.sinhviens = sinhviens;
    }




}


