package javaapplication1.Pojo;
// Generated Aug 21, 2019 1:01:46 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lopkhoabieu generated by hbm2java
 */
@Entity
@Table(name="lopkhoabieu"
    ,catalog="quanlysinhvien"
)
public class Lopkhoabieu  implements java.io.Serializable {


     private String maLopKhoaBieu;
     private String tenMonHoc;

    public Lopkhoabieu() {
    }

	
    public Lopkhoabieu(String maLopKhoaBieu) {
        this.maLopKhoaBieu = maLopKhoaBieu;
    }
    public Lopkhoabieu(String maLopKhoaBieu, String tenMonHoc) {
       this.maLopKhoaBieu = maLopKhoaBieu;
       this.tenMonHoc = tenMonHoc;
    }
   
     @Id 

    
    @Column(name="MaLopKhoaBieu", unique=true, nullable=false, length=100)
    public String getMaLopKhoaBieu() {
        return this.maLopKhoaBieu;
    }
    
    public void setMaLopKhoaBieu(String maLopKhoaBieu) {
        this.maLopKhoaBieu = maLopKhoaBieu;
    }

    
    @Column(name="TenMonHoc", length=100)
    public String getTenMonHoc() {
        return this.tenMonHoc;
    }
    
    public void setTenMonHoc(String tenMonHoc) {
        this.tenMonHoc = tenMonHoc;
    }




}


