package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Phuckhao generated by hbm2java
 */
@Entity
@Table(name="phuckhao"
    ,catalog="quanlysinhvien"
)
public class Phuckhao  implements java.io.Serializable {


     private PhuckhaoId id;
     private String monPhucKhao;
     private String trangThai;
     private String hoTen;
     private String cotDiemPhucKhao;
     private String diemMongMuon;
     private String lyDo;

    public Phuckhao() {
    }

	
    public Phuckhao(PhuckhaoId id) {
        this.id = id;
    }
    public Phuckhao(PhuckhaoId id, String monPhucKhao, String trangThai, String hoTen, String cotDiemPhucKhao, String diemMongMuon, String lyDo) {
       this.id = id;
       this.monPhucKhao = monPhucKhao;
       this.trangThai = trangThai;
       this.hoTen = hoTen;
       this.cotDiemPhucKhao = cotDiemPhucKhao;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maPhucKhao", column=@Column(name="MaPhucKhao", nullable=false, length=50) ), 
        @AttributeOverride(name="ngayBd", column=@Column(name="NgayBD", nullable=false, length=19) ), 
        @AttributeOverride(name="ngayKt", column=@Column(name="NgayKT", nullable=false, length=19) ), 
        @AttributeOverride(name="mssv", column=@Column(name="MSSV", nullable=false) ) } )
    public PhuckhaoId getId() {
        return this.id;
    }
    
    public void setId(PhuckhaoId id) {
        this.id = id;
    }

    
    @Column(name="MonPhucKhao")
    public String getMonPhucKhao() {
        return this.monPhucKhao;
    }
    
    public void setMonPhucKhao(String monPhucKhao) {
        this.monPhucKhao = monPhucKhao;
    }

    
    @Column(name="TrangThai")
    public String getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(String trangThai) {
        this.trangThai = trangThai;
    }

    
    @Column(name="HoTen")
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="CotDiemPhucKhao")
    public String getCotDiemPhucKhao() {
        return this.cotDiemPhucKhao;
    }
    
    public void setCotDiemPhucKhao(String cotDiemPhucKhao) {
        this.cotDiemPhucKhao = cotDiemPhucKhao;
    }

    
    @Column(name="DiemMongMuon")
    public String getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(String diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }

    
    @Column(name="LyDo")
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }




}


