package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhuckhaoId generated by hbm2java
 */
@Embeddable
public class PhuckhaoId  implements java.io.Serializable {


     private String maPhucKhao;
     private Date ngayBd;
     private Date ngayKt;
     private String mssv;

    public PhuckhaoId() {
    }

    public PhuckhaoId(String maPhucKhao, Date ngayBd, Date ngayKt, String mssv) {
       this.maPhucKhao = maPhucKhao;
       this.ngayBd = ngayBd;
       this.ngayKt = ngayKt;
       this.mssv = mssv;
    }
   


    @Column(name="MaPhucKhao", nullable=false, length=50)
    public String getMaPhucKhao() {
        return this.maPhucKhao;
    }
    
    public void setMaPhucKhao(String maPhucKhao) {
        this.maPhucKhao = maPhucKhao;
    }


    @Column(name="NgayBD", nullable=false, length=19)
    public Date getNgayBd() {
        return this.ngayBd;
    }
    
    public void setNgayBd(Date ngayBd) {
        this.ngayBd = ngayBd;
    }


    @Column(name="NgayKT", nullable=false, length=19)
    public Date getNgayKt() {
        return this.ngayKt;
    }
    
    public void setNgayKt(Date ngayKt) {
        this.ngayKt = ngayKt;
    }


    @Column(name="MSSV", nullable=false)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhuckhaoId) ) return false;
		 PhuckhaoId castOther = ( PhuckhaoId ) other; 
         
		 return ( (this.getMaPhucKhao()==castOther.getMaPhucKhao()) || ( this.getMaPhucKhao()!=null && castOther.getMaPhucKhao()!=null && this.getMaPhucKhao().equals(castOther.getMaPhucKhao()) ) )
 && ( (this.getNgayBd()==castOther.getNgayBd()) || ( this.getNgayBd()!=null && castOther.getNgayBd()!=null && this.getNgayBd().equals(castOther.getNgayBd()) ) )
 && ( (this.getNgayKt()==castOther.getNgayKt()) || ( this.getNgayKt()!=null && castOther.getNgayKt()!=null && this.getNgayKt().equals(castOther.getNgayKt()) ) )
 && ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaPhucKhao() == null ? 0 : this.getMaPhucKhao().hashCode() );
         result = 37 * result + ( getNgayBd() == null ? 0 : this.getNgayBd().hashCode() );
         result = 37 * result + ( getNgayKt() == null ? 0 : this.getNgayKt().hashCode() );
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         return result;
   }   


}


