package javaapplication1.Pojo;
// Generated Aug 23, 2019 2:10:35 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name="sinhvien"
    ,catalog="quanlysinhvien"
)
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private String hoTen;
     private boolean gioiTinh;
     private String cmnd;
     private String maLop;
     private String maChucVu;

    public Sinhvien() {
    }

	
    public Sinhvien(String mssv, String hoTen, boolean gioiTinh, String cmnd, String maLop) {
        this.mssv = mssv;
        this.hoTen = hoTen;
        this.gioiTinh = gioiTinh;
        this.cmnd = cmnd;
        this.maLop = maLop;
    }
    public Sinhvien(String mssv, String hoTen, boolean gioiTinh, String cmnd, String maLop, String maChucVu) {
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.maLop = maLop;
       this.maChucVu = maChucVu;
    }
   
     @Id 

    
    @Column(name="MSSV", unique=true, nullable=false, length=50)
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }

    
    @Column(name="HoTen", nullable=false, length=200)
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    
    @Column(name="GioiTinh", nullable=false)
    public boolean isGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    
    @Column(name="CMND", nullable=false, length=50)
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    
    @Column(name="MaLop", nullable=false, length=50)
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }

    
    @Column(name="MaChucVu", length=50)
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }




}


